version: '3.8'
services:
  dev:
    container_name: mwalimufinder-dev
    image: node:16
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_MODE=development

  prod:
    container_name: mwalimufinder-prod
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
    ports:
      - "8989:80"
    environment:
      - NODE_ENV=production
      - VITE_MODE=production
    volumes:
      - ./docker/prod/logs/:/var/log/nginx/
